# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish package

on:
  release:
    types: [published]

jobs:
  publish-package:
    name: Publish package redis-caching-manager
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install Redis 6
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Install dependency
        run: npm install

      - name: Format package
        run: npm run format

      - name: Build Package
        run: npm run build

      - name: Test Package
        run: npm run test
        env: 
          REDIS_URL: redis://localhost:6379

      - name: Publish into npm registry
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}